"""Shared, provider-agnostic data contracts for Reality Painter's AI subsystem.

This module holds typed data structures that describe the *shape* of
information passed between AI subsystem collaborators - never the
collaborators themselves. It contains no orchestration, no provider
logic, no HTTP, no analysis algorithms, and no application wiring.

`apps.reality_painter.ai.manager` and `apps.reality_painter.ai.provider`
previously defined `AICapability`, `RequestStatus`, `AIRequest`,
`AIResponse`, `GenerationRecord`, `ProviderHealthStatus`, and
`ProviderHealth` directly. Those definitions now live here, unchanged
in field meaning, defaults, and enum values - `manager.py` and
`provider.py` import them from this module instead of defining them,
so every other module's public behavior (including consumers that
import these types from `manager.py`, which re-exports them for
compatibility) is unaffected by the move.

This module also defines a typed, optional contract for sketch
analysis output. Today, `apps.reality_painter.ai.sketch_analyzer`
returns a plain `Dict[str, Any]`, and both `manager.py` (via the
`SketchAnalyzer` Protocol) and `prompt_builder.py` (via
`_build_sketch_section`) treat that dict as opaque.
`SketchAnalysisResult` mirrors that dict's existing fields/terminology
exactly, so it's purely additive: nothing currently constructs or
requires it, and adopting it later requires no change to this file.

Dependency rule: this module imports nothing from `manager.py`,
`provider.py`, `prompt_builder.py`, `sketch_analyzer.py`, or any other
application module - it sits at the bottom of the AI subsystem's
dependency graph, standard library only.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


# --- Capabilities and lifecycle -----------------------------------------


class AICapability(str, Enum):
    """A distinct kind of work a provider can be asked to perform.

    Selection is always driven by capability, never by a provider's
    identity or type - adding a future capability (e.g. 3D generation or
    image editing) means adding a member here and registering a provider
    that supports it. `AIManager` itself never changes.
    """

    IMAGE_GENERATION = "image_generation"
    IMAGE_EDIT = "image_edit"
    MODEL_3D_GENERATION = "model_3d_generation"


class RequestStatus(str, Enum):
    """Lifecycle state of a single `AIRequest`."""

    PENDING = "pending"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"


# --- Request/response data -----------------------------------------------


@dataclass
class AIRequest:
    """A single, provider-agnostic request dispatched to the AI subsystem.

    Attributes:
        request_id: Unique id, generated by `AIManager`.
        capability: The kind of work being requested.
        prompt: The finished prompt text - already built by a
            `PromptBuilder`, or passed through as-is if none is
            configured.
        sketch_analysis: Structured sketch data produced by a
            `SketchAnalyzer`, if one is configured and a sketch was
            supplied for this request. `None` otherwise.
        context: Arbitrary caller-supplied context, passed through to
            the prompt builder and made available to the provider.
        status: Current lifecycle status. Mutated in place by
            `AIManager` as the request progresses.
        created_at: Wall-clock creation time (`time.time()`).
        canvas_image: The raw sketch/canvas pixels this request was
            built from (e.g. a `numpy.ndarray`), passed through
            unmodified by `AIManager` alongside `sketch_analysis` so a
            provider capable of true image-to-image generation has the
            actual pixels to send. Opaque to `AIManager` itself. `None`
            if the request has no associated image.
    """

    request_id: str
    capability: AICapability
    prompt: str
    sketch_analysis: Optional[Dict[str, Any]] = None
    context: Dict[str, Any] = field(default_factory=dict)
    status: RequestStatus = RequestStatus.PENDING
    created_at: float = field(default_factory=time.time)
    canvas_image: Optional[Any] = None


@dataclass
class AIResponse:
    """The outcome of a single `AIRequest`.

    Attributes:
        request_id: Matches the originating `AIRequest.request_id`.
        success: Whether the request completed without error.
        provider_name: Name of the provider that produced this response,
            or `None` if a provider never ran (e.g. selection failed, or
            the response was served from cache).
        data: Provider-specific result payload. `AIManager` never
            inspects its contents - only the caller and the provider
            that produced it know its shape.
        error: A human-readable error message if `success` is False,
            otherwise `None`.
        cached: True if this response was served from the cache rather
            than a live provider call.
        completed_at: Wall-clock completion time (`time.time()`).
    """

    request_id: str
    success: bool
    provider_name: Optional[str] = None
    data: Any = None
    error: Optional[str] = None
    cached: bool = False
    completed_at: float = field(default_factory=time.time)


@dataclass(frozen=True)
class GenerationRecord:
    """One completed entry in the AI generation history.

    Pairs a request with its response so a caller (or a future history
    UI) can review what was asked and what came back without a separate
    lookup step.
    """

    request: AIRequest
    response: AIResponse


# --- Provider health -----------------------------------------------------


class ProviderHealthStatus(str, Enum):
    """Coarse-grained health state of a provider."""

    HEALTHY = "healthy"
    DEGRADED = "degraded"
    UNAVAILABLE = "unavailable"
    UNKNOWN = "unknown"


@dataclass(frozen=True)
class ProviderHealth:
    """The result of a single provider health check.

    Attributes:
        status: Coarse-grained health state.
        message: Human-readable detail (e.g. an error summary), or
            `None` if there's nothing more to say than `status`.
        checked_at: Wall-clock time the check was performed
            (`time.time()`).
    """

    status: ProviderHealthStatus
    message: Optional[str] = None
    checked_at: float = field(default_factory=time.time)


# --- Drawing bounds -------------------------------------------------------


@dataclass(frozen=True)
class DrawingBounds:
    """Bounding box of all stroke pixels on the canvas.

    Mirrors `sketch_analyzer._BoundsAnalyzer`'s `"bounds"` output
    exactly (`x_min`, `y_min`, `x_max`, `y_max`, `width`, `height`).
    """

    x_min: int
    y_min: int
    x_max: int
    y_max: int
    width: int
    height: int


# --- Composition ------------------------------------------------------


@dataclass(frozen=True)
class CompositionGrid:
    """Per-cell stroke density over an N x N grid.

    Mirrors `sketch_analyzer._CompositionAnalyzer`'s `"composition"`
    output: cells are keyed as `"row{row}_col{col}"`, each mapping to a
    density value in [0, 1].
    """

    density_by_cell: Dict[str, float] = field(default_factory=dict)


# --- Stroke statistics --------------------------------------------------


@dataclass(frozen=True)
class StrokeStatistics:
    """Aggregate statistics about distinct stroke components.

    Mirrors `sketch_analyzer._StrokeStatisticsAnalyzer`'s
    `"stroke_statistics"` output.
    """

    stroke_count: int
    total_stroke_pixels: int
    average_component_area: float


# --- Relative positions -------------------------------------------------


@dataclass(frozen=True)
class RelativePosition:
    """Normalized centroid position of one stroke component.

    Mirrors one entry of `sketch_analyzer._RelativePositionAnalyzer`'s
    `"relative_positions"` list.
    """

    x: float
    y: float
    area: float


# --- Complexity ---------------------------------------------------------


@dataclass(frozen=True)
class DrawingComplexity:
    """Estimated overall drawing complexity.

    Mirrors `sketch_analyzer._ComplexityAnalyzer`'s `"complexity"`
    output. `level` is one of `"low"`, `"medium"`, `"high"`, matching
    that component's existing thresholds/terminology verbatim.
    """

    level: str
    edge_density: float


# --- Shapes ---------------------------------------------------------------


@dataclass(frozen=True)
class ShapeSummary:
    """Tally of classified contour shapes and the dominant one.

    Mirrors `sketch_analyzer._ShapeAnalyzer`'s `"shapes"` and
    `"dominant_geometry"` outputs. Shape keys are the same strings that
    component already produces: `"line"`, `"triangle"`, `"rectangle"`,
    `"circle"`, `"polygon"`.
    """

    counts_by_shape: Dict[str, int] = field(default_factory=dict)
    dominant_geometry: Optional[str] = None


# --- Objects ------------------------------------------------------------


@dataclass(frozen=True)
class ObjectBounds:
    """Pixel-space bounding box of a candidate object."""

    x: int
    y: int
    width: int
    height: int


@dataclass(frozen=True)
class SketchObject:
    """One candidate "object" - a sufficiently large stroke cluster.

    Mirrors one entry of `sketch_analyzer._ObjectAnalyzer`'s
    `"objects"` list. Intended to remain valid whether the underlying
    detection is the current connected-component heuristic or a future
    real object-detection component - see that module's docstring.
    """

    bounds: ObjectBounds
    area: float


# --- Aggregate result -----------------------------------------------------


@dataclass(frozen=True)
class SketchAnalysisResult:
    """Structured, typed view of a sketch analysis.

    A typed counterpart to the `Dict[str, Any]` that
    `apps.reality_painter.ai.sketch_analyzer.SketchAnalyzer.analyze()`
    currently returns and that `AIManager`/`PromptBuilder` currently
    consume as an opaque mapping. Every field is optional, matching the
    existing behavior where a component contributes nothing (e.g. a
    blank canvas, or a disabled/removed component) rather than raising.

    This type is purely additive: nothing in the existing pipeline
    constructs or requires it today.
    """

    bounds: Optional[DrawingBounds] = None
    canvas_utilization: Optional[float] = None
    empty_space_ratio: Optional[float] = None
    composition: Optional[CompositionGrid] = None
    stroke_statistics: Optional[StrokeStatistics] = None
    relative_positions: List[RelativePosition] = field(default_factory=list)
    complexity: Optional[DrawingComplexity] = None
    shapes: Optional[ShapeSummary] = None
    objects: List[SketchObject] = field(default_factory=list)